apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dpat-configuration.1
  title: DPAT Configuration
  description: Create a DPAT Configuration artifact
  annotations:
    backstage.io/techdocs-ref: dir:.
  mesh:
    icon: https://cdn-icons-png.flaticon.com/512/8187/8187143.png
  tags:
    - dpat
spec:
  generates: componenttype:default/workload
  owner: rabobank
  type: workload
  parameters:
    - title: DPAT Witboost Metadata
      description: Parameters for the DPAT Configuration template
      type: object
      required:
        - name
        - domain
        - dataproduct
        - dataProductRepo
        - dataProductRootDirectory
        - identifier
      properties:
        name:
          title: Name
          type: string
          description: Required name used for display purposes
          ui:field: EntityNamePicker
          default: DPAT Configuration
          ui:options:
            allowArbitraryValues: true
        domain:
          title: Domain
          type: string
          description: Domain of the Data Product this DPAT configuration artifact belongs to
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
        dataproduct:
          title: Data Product
          type: string
          description: Data Product this DPAT configuration artifact belongs to
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
        dataProductRepo:
          title: Data Product Repository
          type: string
          description: DPAT Configuration artifact will be created into this repository
          default: rabo-wit-dp-${{ parameters.domain | replace(r/domain:| |-/, "") }}-${{ parameters.name.split(" ") | join("") | lower }}
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: gitlab.com?owner=manuelscurti&repo=dpat-configuration-template
          ui:options:
            allowArbitraryValues: false
        dataProductRootDirectory:
          title: Data Product Root Directory
          type: string
          default: /components/${{ "dc-" + parameters.name.toLocaleLowerCase().split(" ").join("") }}
          description: Root directory of the Data Product repository where the DPAT Configuration artifact will be created
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: https://github.com/abhi4u-here/rabobank-witboost
          ui:options:
            allowArbitraryValues: false

        identifier:
          title: Identifier
          type: string
          description: A unique identifier for the entity inside the domain. It will not be editable after creation and is expected to be a string that is sequences of [a-zA-Z] separated by any of [-_]
          ui:field: ComponentIdentifierPicker
          ui:options:
            allowArbitraryValues: false
        owner:
          title: Component Owner
          type: string
          description: Automatically selected from the Data Product metadata. Data Product owner.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        dependsOn:
          title: Depends on
          type: array
          default: []
          items:
            type: string
            ui:field: EntityComponentsPicker
            ui:fieldName: dataproduct
            ui:options:
              allowArbitraryValues: false

    - title: DPAT Configuration Parameters
      description: Parameters for the DPAT Configuration template
      environmentParameters: true
      type: object
      required:
        - resourceGroupName
        - adlsStorageAccount
        - adlsContainerName
        - databricksSecretKey
        - azureClientId
        - azureTenantId
        - azureScope
        - metadataAPI
        - dataProducerName
        - relativeUrl
      properties:
        resourceGroupName:
          title: Resource Group Name
          type: string
          description: Name of the Azure Resource Group where the DPAT Data Product will be deployed
        adlsStorageAccount:
          title: ADLS Storage Account
          type: string
          description: Name of the ADLS Storage Account to be used in the DPAT Data Product configuration
        adlsContainerName:
          title: ADLS Container Name
          type: string
          description: Name of the ADLS Container to be used in the DPAT Data Product configuration
        databricksSecretKey:
          title: Databricks Secret Key
          type: string
          description: Secret Key of the Databricks workspace to be used in the DPAT Data Product configuration
        azureClientId:
          title: Azure Client ID
          type: string
          description: Client ID of the Azure Service Principal to be used in the DPAT Data Product configuration
        azureTenantId:
          title: Azure Tenant ID
          type: string
          description: Tenant ID of the Azure Service Principal to be used in the DPAT Data Product configuration
        azureScope:
          title: Azure Scope
          type: string
          description: Scope to be used for Azure authentication in the DPAT Data Product configuration
        metadataAPI:
          title: Metadata API URL
          type: string
          description: URL of the Metadata API to be used in the DPAT Data Product configuration
        dataProducerName:
          title: Data Producer Name
          type: string
          description: Name of the Data Producer to be used in the DPAT Data Product configuration
        relativeUrl:
          title: Relative URL
          type: string
          description: Relative URL to be used in the DPAT Data Product configuration

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: &rootDirectory ${{ parameters.dataProductRootDirectory }}${{ "/conf-" + parameters.name.toLocaleLowerCase().split(" ").join("") }}
        values:
          name: ${{ parameters.name }}
          identifier: ${{ parameters.identifier }}
          owner: ${{ parameters.owner }}
          domain: ${{ parameters.domain }}
          dependsOn: ${{ parameters.dependsOn }}
          dataproduct: ${{ parameters.dataproduct }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          adlsStorageAccount: ${{ parameters.adlsStorageAccount }}
          adlsContainerName: ${{ parameters.adlsContainerName }}
          databricksSecretKey: ${{ parameters.databricksSecretKey }}
          azureClientId: ${{ parameters.azureClientId }}
          azureTenantId: ${{ parameters.azureTenantId }}
          azureScope: ${{ parameters.azureScope }}
          metadataAPI: ${{ parameters.metadataAPI }}
          dataProducerName: ${{ parameters.dataProducerName }}
          relativeUrl: ${{ parameters.relativeUrl }}

          useCaseTemplateId: urn:dmb:utm:dpat-configuration-template:1.0.0
          infrastructureTemplateId: urn:dmb:itm:dpat-tech-adapter:1
          # repoUrl: &repoUrl dev.azure.com?organization=raboweb&owner=Tribe%20Data%20and%20Analytics&repo=${{ parameters.dataProductRepo }}

          # Temporary using GitLab until we install this in Rabobank environment
          repoUrl: &repoUrl github.com?owner=systemationbv&repo=${{ parameters.name }}
          useCaseTemplateVersion: 1.0.0
          rootDirectory: *rootDirectory

    # - id: publish
    #   name: Publish
    #   action: witboostMeshComponent:publish:azure
    #   input:
    #     repoUrl: *repoUrl
    #     rootDirectory: .
    #     dataproduct: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: witboostMeshComponent:publish:github
      input:
        allowedHosts: ["github.com"]
        description: "This is ${{ parameters.name }}"
        repoUrl: *repoUrl
        rootDirectory: *rootDirectory
        dataproduct: "${{ parameters.dataproduct }}"

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: "${{ steps.publish.output.repoContentsUrl }}"
        catalogInfoPath: ${{ parameters.dataProductRootDirectory }}${{ "/conf-" + parameters.name.toLocaleLowerCase().split(" ").join("") }}/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: "${{ steps.publish.output.remoteUrl }}"
      - title: Open in catalog
        icon: catalog
        entityRef: "${{ steps.register.output.entityRef }}"
